### ISSUE TITLE
npm start后terminal会不正常的一直刷

### ISSUE THREAD

**Issue by JackieZhang-Coding** [naihe138/GraphQL-demo#12]
启动后，terminal会不停的刷，不知道是什么问题。

**Comment by jinpengqiong** [comment]
一样的一直刷新报错
errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {}
}
(node:39889) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at Pool.emit (events.js:376:20)
    at /Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/connection/pool.js:985:11
    at /Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/connection/connect.js:40:11
    at callback (/Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.<anonymous> (/Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:483:26)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:39889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 516)

**Comment by jinpengqiong** [comment]
一样的一直刷新报错
errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {}
}
(node:39889) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at Pool.emit (events.js:376:20)
    at /Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/connection/pool.js:985:11
    at /Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/connection/connect.js:40:11
    at callback (/Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.<anonymous> (/Users/admin/Desktop/GraphQL-demo/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:483:26)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:39889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 516)

**Comment by binghong-chen** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/10174446/217609213-5486cca9-ad5c-4934-882f-e4b56507c7a2.png">
需要mongodb环境
